In [1]:
import pandas as pd

In [2]:
from autodesk import AutodeskAPIClient

In [3]:
CLIENT_ID = "mi4oNfLstbonAnedHx4XpF3kOdAwc0MlRdRbAdYhWmWxDiiI"
CLIENT_SECRET = "YfFG5SdhLVqDXujDACk86MDprhJ08yRtRX1bJtnvdkHYxmf9iXWMcOS0e3sfaiLA"
ACCOUNT_ID = "ff580791-c0f5-4839-954c-11cd09d8cf69"

In [4]:
APS_CLIENT_ID = "mi4oNfLstbonAnedHx4XpF3kOdAwc0MlRdRbAdYhWmWxDiiI"
APS_CLIENT_SECRET = "YfFG5SdhLVqDXujDACk86MDprhJ08yRtRX1bJtnvdkHYxmf9iXWMcOS0e3sfaiLA"
SSA_OXYGEN_ID = "HRB2JPVHPD6Z4NUW"
KEY_ID = "b7b5138d-f354-4b76-8945-213eaee9065f"
PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAnBD5T5ydmlIxO/L9ucTcgB94gUPJVp+O4aOWJxzHvlE+jA/d
LheMrm5DfcFFDwap1Qd4btVySUtf+SuPpB3DhOOAms+k2wSUaCYA5eg2t0dJ/1/c
oujsnR9ONArf0J4MSjhN4GPKU0a3Ahlx4XBH52pPKjNQyW3JOunyAi10Z1ViSf4l
AD3MuiDZF6kYbQjnUQLR2Erza1+eDbsVcwtuaYKOfi3END3eH0AypMaWHIrlR7QO
gUpZ8RcaMOQngZuHpzeYP/sXzdZZqZEZ6ykph/cDZZY41TT7FY/PNwnc3uAYnpwB
5PcSg6P0hIIuBcuvobwmW9qnjLl+nDmg7QhhaQIDAQABAoIBAAU2L3gF83xj6DKj
IJQt8nXRkqbw//SzHpJnn3vr0Lo2nGnH5o3acviNhHHR86/STlKDG3WmDgbL7B3f
NaM82e0HK71NczI3UtQdrQ+AaF1bZ9c7mOTv9a6O1lJTzVnMbxAh3pFSsqNwW9ms
IhGtu+KvXnh66CTF3XaNS/Bymu3GjpFWXKWoLGiErbnz+MLf1+NQYm+RJFoVosj6
fYKjxwl1F61mrmskbRSnVAruhViO8Xt2lDQ8PNBokux5ZdXJhwFB9AWOay+7szDX
buEbBHlabkPq+zW+KBjqSoQaPHQYLivx51BrscaDiLP3npyNB/gMIrqC1CVJtjII
hP9RrjUCgYEAyrNFm0JF8O/yIt0RQbFXkbZhFtFdtGFDgRgRXTDdgrjBUp4EArGl
81w6MxUSGgSZMkKdubwL0okZOvSLXlP5/9PGBILYPA3wb2gLxvFRZBZ4JGoukSpz
H6S9r9LuS+3oSe0gsddPk+sNCy6NXqbdSOortPO7VB6ZfTkxKb8+UFUCgYEAxRqL
mv9hod2ZJC9bc47TUEv5F8WGhAO/rYM37EEtL4Ub0nzbW+f4B8dOyoeQUwKM179z
p/slf86IIyIOnR2/P9ZfdaRlG5uIYPqXX/SYZmwDXv5VdHCiDQMhNFzSWNFx3OQQ
VNDDuYr68KE2MWl5v1YAIwagerlEimRslBcSUMUCgYABs3t0EBxSJ1Fa5YwNhxV7
DZLHBD7LEr3kSXVr2MsjG7XToava8e64mh+K6jRar4sxlsmIE4Ht5GSn0AGTaxUA
BqD0zLxP1LYd2TuwEbpjIqUjeRim8zpAG7vTy+tgC8EVTb4mf+4VCbX0UBGzp6bX
w89WF22NCSy0llRJS2eUeQKBgFaZNSEid0jgzboCPJHm/JzY5FY3aMRzyTF454cb
k7i/KNwwE0isAGOag9mj+hsekbbw3OW/CFjA6ztUaUtKmI55p3NOiUW57g99yihU
lOjbKBgCcpU4L1q8N0iER77SNs6wPSSmnHfWwi4bBm5rQxx3spOxA60n3R9YxAPE
pz1pAoGAJaLnb81N8VcnWm0liJFtRbmiJa3CCPRalfXrjwTBJYlmB1Q0QDBpHsU3
VgcZddUMDTGwlWHpxVz+e8sfQfvpEZuLur/W86UgIN9fPf0vR6zYVLblLZaLdQ/j
KAa1BDCI9chaZAFVthoMkYypA1SBBmvtW0AjxzbaAbm5/veil2Y=
-----END RSA PRIVATE KEY-----"""

##SCOPE = "data:read"  ## for data inside of projects
SCOPE = "account:read" ## for projects

In [5]:
Projects = AutodeskAPIClient(
    aps_client_id= APS_CLIENT_ID,
    aps_client_secret= APS_CLIENT_SECRET,
    ssa_oxygen_id= SSA_OXYGEN_ID,
    key_id= KEY_ID,
    private_key= PRIVATE_KEY,
    ## account_id=ACCOUNT_ID,
    scope= SCOPE  # optional, defaults to projects if omitted
)

In [6]:
access_token = Projects.get_ssa_access_token()

In [ ]:
df_projects = Projects.get_all_projects(access_token)
display(df_projects)

In [8]:
# Pull only project in ACC module, projects in production, and active projects
df_filtered = df_projects[(df_projects['platform'] == 'acc') & (df_projects['classification'] == 'production') & (df_projects['status'] == 'active')]
## display(df_filtered)

### Get Forms Header
The scope needs to be changed to pull forms

In [9]:
# Change scope
Projects.scope = "data:read"
Projects.scope

'data:read'

In [10]:
# Update scope & get new token
access_token = Projects.get_ssa_access_token()

In [11]:
test_project_id = "b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c"
forms = Projects.get_project_forms(access_token, test_project_id)
print(len(forms))

0

In [12]:
import requests
import pandas as pd

def get_project_forms(access_token: str, project_id: str) -> pd.DataFrame:
    access_token = access_token.strip()

    headers = {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/json",
    }

    url = (
        f"https://developer.api.autodesk.com/construction/forms/v1/"
        f"projects/{project_id}/forms?limit=50&offset=0"
    )

    response = requests.get(url, headers=headers, timeout=60)

    if response.status_code != 200:
        raise RuntimeError(
            f"Request failed with status {response.status_code}: {response.text}"
        )

    data = response.json()
    forms = data.get("data", [])

    return pd.json_normalize(forms)

In [13]:
test_project_id = "b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c"
df_forms = get_project_forms(access_token, test_project_id)
display(df_forms)

,projectId,id,status,formNum,formDate,name,assigneeId,assigneeType,dueDate,locationId,...,weather.precipitationAccumulationUnit,weather.temperatureMin,weather.temperatureMax,weather.temperatureUnit,weather.humidity,weather.windSpeed,weather.windGust,weather.speedUnit,weather.windBearing,weather.hourlyWeather
0,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,6211d78f-6460-49df-a5ee-2f7d79520b09,draft,2,2025-09-22,Daily Safety Inspection,NaN,NaN,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,1f0dc803-6c2b-4bec-a62d-4f37a4dae02a,draft,5,2025-11-05,Project Setup Form,NaN,NaN,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,866c341c-63d4-45e6-b1c3-7133931d02ea,draft,18,2025-11-12,Daily Safety Inspection,NaN,NaN,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,adef8c6a-9d93-4e35-a07b-795947f5949a,draft,28,2025-11-19,Trade Partner Daily Report,USK2AGWCQWWZXCBS,user,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,770621e9-4283-46b6-9623-0d9aadf4ad18,draft,33,2025-11-24,Trade Partner Daily Report,GGHXNZQ99T3A,user,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,76f8d4bd-cd0d-4d0b-94bb-58296244645d,submitted,40,2025-12-02,Daily Safety Inspection,NaN,NaN,2025-12-02,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,60f9ca92-a4ae-42a2-9865-f7d5b97e8bf0,submitted,46,2025-12-09,Daily Safety Inspection,NaN,NaN,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,8588fa0d-08aa-45f4-be38-f1444276d68c,submitted,48,2025-12-10,Daily Safety Inspection,NaN,NaN,2025-12-10,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,09a4fd92-b0dc-4c7f-a2cf-cb80fae6abfe,submitted,50,2025-12-11,Daily Safety Inspection,NaN,NaN,2025-12-11,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f92b5fec-2c5c-4e36-acdf-a933df57c59f,submitted,52,2025-12-15,Daily Safety Inspection,NaN,NaN,2025-12-15,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,92c8f7ea-80b3-4002-a19b-3a4b34ab4629,submitted,54,2025-12-16,Daily Safety Inspection,NaN,NaN,2025-12-16,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,aa979fad-ef2a-4f52-a3df-4669da519322,submitted,56,2025-12-17,Daily Safety Inspection,NaN,NaN,2025-12-17,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,d4a11022-7cbc-45b9-845b-e8a6263c5818,submitted,57,2025-12-18,Daily Safety Inspection,NaN,NaN,2025-12-18,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,4028918e-4fd6-4dfb-9648-b30aadf043e4,submitted,60,2025-12-19,Daily Safety Inspection,NaN,NaN,2025-12-19,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,b2a4ae10-f50f-4e5e-9541-b6077760c450,draft,64,2025-12-29,EHS Violation Warning,4ZHJ2BG2PSMQNDKT,user,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f690bfa0-8451-4fd4-8030-d32a65c716c1,submitted,66,2025-12-29,Daily Safety Inspection,NaN,NaN,2025-12-29,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f7bea8ef-0a38-430e-b036-bb6b39c2b141,submitted,77,2026-01-08,Inspection Request,9FK2QG6NRDY4U7DX,user,2026-01-08,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,21a496a4-0fd9-4dee-9aaa-5291b1e08cac,draft,78,2026-01-08,Inspection Request,4ZHJ2BG2PSMQNDKT,user,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,5c77855c-04e2-4b70-8575-d51b6d7540dc,submitted,84,2026-01-09,Daily Safety Inspection,NaN,NaN,2026-01-09,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,35343724-8847-4787-b1c9-072fdbeeae36,submitted,80,2026-01-08,Daily Safety Inspection,NaN,NaN,2026-01-08,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,e04ce04d-17dd-4487-a8c7-000238d8c3c1,submitted,74,2026-01-06,Daily Safety Inspection,NaN,NaN,2026-01-06,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,b66817d2-66eb-4ec6-b885-a6cec2bc1dea,submitted,24,2025-11-14,Daily Safety Inspection,NaN,NaN,2025-11-14,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,9338823a-9b7d-46ef-b779-14ed73715ffb,submitted,72,2026-01-05,Daily Safety Inspection,NaN,NaN,2026-01-05,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,2b5c2438-87f8-4127-a9fc-950227eed960,submitted,70,2026-01-02,Daily Safety Inspection,NaN,NaN,2026-01-02,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,bdcafd4b-06e0-41f9-831b-803b273d34e9,submitted,86,2026-01-12,Daily Safety Inspection,NaN,NaN,2026-01-12,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,308b85f2-47b1-4496-8504-a657af78bf15,submitted,88,2026-01-13,Daily Safety Inspection,NaN,NaN,2026-01-13,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,0777ec89-47ea-42a6-8a1f-06b79f9a9cb5,submitted,41,2025-12-03,Daily Safety Inspection,NaN,NaN,2025-12-03,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,ade095db-3247-497a-b64f-27af6a6df106,submitted,20,2025-11-12,Daily Safety Inspection,NaN,NaN,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,7b1fba8d-29b3-4099-b7a1-b83953c703c4,submitted,68,2025-12-31,Daily Safety Inspection,NaN,NaN,2025-12-31,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,659aabc2-0bb8-436f-b7f6-5e816d395a7e,submitted,85,2026-01-12,XL Daily Report (DCR),NaN,NaN,2026-01-12,None,...,cm,4.5,16.0,Celsius,0.72,3.7,NaN,km/h,338.0,"[{'id': 70892706, 'hour': '07:00:00', 'temp': ..."
30,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,4ba7e3d8-f187-4159-ad4a-eb7a06219fb6,submitted,87,2026-01-13,XL Daily Report (DCR),NaN,NaN,2026-01-13,None,...,cm,4.7,17.1,Celsius,0.70,2.7,NaN,km/h,317.0,"[{'id': 70892709, 'hour': '07:00:00', 'temp': ..."
31,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,c4f00682-8f53-41ef-a762-708f33b73212,submitted,92,2026-01-15,Daily Safety Inspection,NaN,NaN,2026-01-15,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,77dbbe01-6ca0-4f8e-b8e2-d3b84597749f,submitted,94,2026-01-16,Daily Safety Inspection,NaN,NaN,2026-01-16,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,08aeb746-65b8-4706-b7e3-f5dc9725a9ed,submitted,96,2026-01-20,Daily Safety Inspection,NaN,NaN,2026-01-20,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,3c7a0544-ea01-42e7-9f55-fe2f0e127840,submitted,98,2026-01-21,Daily Safety Inspection,NaN,NaN,2026-01-21,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,d055bac6-bfa9-4552-a0cc-b8efdff247a9,submitted,100,2026-01-22,Daily Safety Inspection,NaN,NaN,2026-01-22,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,c47ab3cc-19dd-469b-88ce-400bc1b228e7,submitted,103,2026-01-24,Daily Safety Inspection,NaN,NaN,2026-01-24,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,dc7726a2-1a84-4fe2-b7ba-ff4a99aeba28,submitted,102,2026-01-24,XL Daily Report (DCR),NaN,NaN,2026-01-24,None,...,cm,4.8,18.9,Celsius,0.61,6.8,NaN,km/h,339.0,"[{'id': 71709612, 'hour': '07:00:00', 'temp': ..."
38,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f62c5bc9-6b94-4b3a-96b5-94c2df9277f7,submitted,107,2026-01-26,Daily Safety Inspection,NaN,NaN,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f0d00afa-f66b-4d1f-9a48-b87bef3646f8,submitted,105,2026-01-26,Daily Safety Inspection,NaN,NaN,2026-01-26,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,956e475a-305a-435a-ab3e-df85d12c60f5,submitted,109,2026-01-27,Daily Safety Inspection,NaN,NaN,2026-01-27,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,25924760-071a-4738-a1ac-caf8af647870,draft,113,2026-01-28,Trade Partner Daily Report,4ZHJ2BG2PSMQNDKT,user,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,d94fb011-db9e-4f6f-80c9-b3ac289b403d,submitted,112,2026-01-28,Daily Safety Inspection,NaN,NaN,2026-01-28,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,c0a6148e-16ae-4c65-a84d-8203b1fe8d5d,submitted,115,2026-01-29,Daily Safety Inspection,NaN,NaN,2026-01-29,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,ba042446-706c-4861-9104-b62bb4f50dba,submitted,117,2026-01-30,Daily Safety Inspection,NaN,NaN,2026-01-30,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,afea122d-91f4-401d-bc56-b6895c2c9a78,submitted,90,2026-01-14,Daily Safety Inspection,NaN,NaN,2026-01-14,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,c1d8d036-a854-4b6a-93c9-592b0b824dec,submitted,89,2026-01-14,XL Daily Report (DCR),NaN,NaN,2026-01-14,None,...,cm,5.5,17.1,Celsius,0.70,2.1,NaN,km/h,310.0,"[{'id': 70892712, 'hour': '07:00:00', 'temp': ..."
47,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,faccd2c3-885c-490a-89f5-27b4e5d7a6f1,submitted,91,2026-01-15,XL Daily Report (DCR),NaN,NaN,2026-01-15,None,...,cm,6.4,19.3,Celsius,0.69,3.5,NaN,km/h,323.0,"[{'id': 71024448, 'hour': '07:00:00', 'temp': ..."
48,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,d270c910-d65e-452c-8af1-50842bb5c323,submitted,93,2026-01-16,XL Daily Report (DCR),NaN,NaN,2026-01-16,None,...,cm,4.9,18.3,Celsius,0.70,1.9,NaN,km/h,231.0,"[{'id': 71125311, 'hour': '07:00:00', 'temp': ..."
49,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f5ed09fc-af15-491d-abd2-39cd4ed94ffa,submitted,95,2026-01-20,XL Daily Report (DCR),NaN,NaN,2026-01-20,None,...,cm,5.4,13.1,Celsius,0.84,2.9,NaN,km/h,289.0,"[{'id': 71367822, 'hour': '07:00:00', 'temp': ..."

In [14]:
df_forms_filtered = df_forms[df_forms["formTemplate.templateType"].str.contains("safety")]
display(df_forms_filtered)

,projectId,id,status,formNum,formDate,name,assigneeId,assigneeType,dueDate,locationId,...,weather.precipitationAccumulationUnit,weather.temperatureMin,weather.temperatureMax,weather.temperatureUnit,weather.humidity,weather.windSpeed,weather.windGust,weather.speedUnit,weather.windBearing,weather.hourlyWeather
0,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,6211d78f-6460-49df-a5ee-2f7d79520b09,draft,2,2025-09-22,Daily Safety Inspection,NaN,NaN,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,866c341c-63d4-45e6-b1c3-7133931d02ea,draft,18,2025-11-12,Daily Safety Inspection,NaN,NaN,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,76f8d4bd-cd0d-4d0b-94bb-58296244645d,submitted,40,2025-12-02,Daily Safety Inspection,NaN,NaN,2025-12-02,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,60f9ca92-a4ae-42a2-9865-f7d5b97e8bf0,submitted,46,2025-12-09,Daily Safety Inspection,NaN,NaN,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,8588fa0d-08aa-45f4-be38-f1444276d68c,submitted,48,2025-12-10,Daily Safety Inspection,NaN,NaN,2025-12-10,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,09a4fd92-b0dc-4c7f-a2cf-cb80fae6abfe,submitted,50,2025-12-11,Daily Safety Inspection,NaN,NaN,2025-12-11,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f92b5fec-2c5c-4e36-acdf-a933df57c59f,submitted,52,2025-12-15,Daily Safety Inspection,NaN,NaN,2025-12-15,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,92c8f7ea-80b3-4002-a19b-3a4b34ab4629,submitted,54,2025-12-16,Daily Safety Inspection,NaN,NaN,2025-12-16,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,aa979fad-ef2a-4f52-a3df-4669da519322,submitted,56,2025-12-17,Daily Safety Inspection,NaN,NaN,2025-12-17,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,d4a11022-7cbc-45b9-845b-e8a6263c5818,submitted,57,2025-12-18,Daily Safety Inspection,NaN,NaN,2025-12-18,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,4028918e-4fd6-4dfb-9648-b30aadf043e4,submitted,60,2025-12-19,Daily Safety Inspection,NaN,NaN,2025-12-19,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,b2a4ae10-f50f-4e5e-9541-b6077760c450,draft,64,2025-12-29,EHS Violation Warning,4ZHJ2BG2PSMQNDKT,user,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f690bfa0-8451-4fd4-8030-d32a65c716c1,submitted,66,2025-12-29,Daily Safety Inspection,NaN,NaN,2025-12-29,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,5c77855c-04e2-4b70-8575-d51b6d7540dc,submitted,84,2026-01-09,Daily Safety Inspection,NaN,NaN,2026-01-09,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,35343724-8847-4787-b1c9-072fdbeeae36,submitted,80,2026-01-08,Daily Safety Inspection,NaN,NaN,2026-01-08,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,e04ce04d-17dd-4487-a8c7-000238d8c3c1,submitted,74,2026-01-06,Daily Safety Inspection,NaN,NaN,2026-01-06,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,b66817d2-66eb-4ec6-b885-a6cec2bc1dea,submitted,24,2025-11-14,Daily Safety Inspection,NaN,NaN,2025-11-14,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,9338823a-9b7d-46ef-b779-14ed73715ffb,submitted,72,2026-01-05,Daily Safety Inspection,NaN,NaN,2026-01-05,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,2b5c2438-87f8-4127-a9fc-950227eed960,submitted,70,2026-01-02,Daily Safety Inspection,NaN,NaN,2026-01-02,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,bdcafd4b-06e0-41f9-831b-803b273d34e9,submitted,86,2026-01-12,Daily Safety Inspection,NaN,NaN,2026-01-12,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,308b85f2-47b1-4496-8504-a657af78bf15,submitted,88,2026-01-13,Daily Safety Inspection,NaN,NaN,2026-01-13,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,0777ec89-47ea-42a6-8a1f-06b79f9a9cb5,submitted,41,2025-12-03,Daily Safety Inspection,NaN,NaN,2025-12-03,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,ade095db-3247-497a-b64f-27af6a6df106,submitted,20,2025-11-12,Daily Safety Inspection,NaN,NaN,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,7b1fba8d-29b3-4099-b7a1-b83953c703c4,submitted,68,2025-12-31,Daily Safety Inspection,NaN,NaN,2025-12-31,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,c4f00682-8f53-41ef-a762-708f33b73212,submitted,92,2026-01-15,Daily Safety Inspection,NaN,NaN,2026-01-15,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,77dbbe01-6ca0-4f8e-b8e2-d3b84597749f,submitted,94,2026-01-16,Daily Safety Inspection,NaN,NaN,2026-01-16,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,08aeb746-65b8-4706-b7e3-f5dc9725a9ed,submitted,96,2026-01-20,Daily Safety Inspection,NaN,NaN,2026-01-20,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,3c7a0544-ea01-42e7-9f55-fe2f0e127840,submitted,98,2026-01-21,Daily Safety Inspection,NaN,NaN,2026-01-21,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,d055bac6-bfa9-4552-a0cc-b8efdff247a9,submitted,100,2026-01-22,Daily Safety Inspection,NaN,NaN,2026-01-22,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,c47ab3cc-19dd-469b-88ce-400bc1b228e7,submitted,103,2026-01-24,Daily Safety Inspection,NaN,NaN,2026-01-24,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f62c5bc9-6b94-4b3a-96b5-94c2df9277f7,submitted,107,2026-01-26,Daily Safety Inspection,NaN,NaN,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f0d00afa-f66b-4d1f-9a48-b87bef3646f8,submitted,105,2026-01-26,Daily Safety Inspection,NaN,NaN,2026-01-26,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,956e475a-305a-435a-ab3e-df85d12c60f5,submitted,109,2026-01-27,Daily Safety Inspection,NaN,NaN,2026-01-27,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,d94fb011-db9e-4f6f-80c9-b3ac289b403d,submitted,112,2026-01-28,Daily Safety Inspection,NaN,NaN,2026-01-28,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,c0a6148e-16ae-4c65-a84d-8203b1fe8d5d,submitted,115,2026-01-29,Daily Safety Inspection,NaN,NaN,2026-01-29,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,ba042446-706c-4861-9104-b62bb4f50dba,submitted,117,2026-01-30,Daily Safety Inspection,NaN,NaN,2026-01-30,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,afea122d-91f4-401d-bc56-b6895c2c9a78,submitted,90,2026-01-14,Daily Safety Inspection,NaN,NaN,2026-01-14,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_forms_filtered.columns

Index(['projectId', 'id', 'status', 'formNum', 'formDate', 'name',
       'assigneeId', 'assigneeType', 'dueDate', 'locationId', 'createdBy',
       'createdAt', 'userCreatedAt', 'notes', 'description', 'updatedAt',
       'customValues', 'weather', 'lastSubmitterSignature',
       'formTemplate.projectId', 'formTemplate.id', 'formTemplate.name',
       'formTemplate.status', 'formTemplate.templateType',
       'tabularValues.worklogEntries', 'tabularValues.materialsEntries',
       'tabularValues.equipmentEntries', 'pdfValues', 'pdfUrl',
       'weather.provider', 'weather.summaryKey',
       'weather.precipitationAccumulation',
       'weather.precipitationAccumulationUnit', 'weather.temperatureMin',
       'weather.temperatureMax', 'weather.temperatureUnit', 'weather.humidity',
       'weather.windSpeed', 'weather.windGust', 'weather.speedUnit',
       'weather.windBearing', 'weather.hourlyWeather'],
      dtype='str')

In [ ]:
cols_to_keep = ['projectId', 'id', 'formNum','formDate','formTemplate.templateType','name','assigneeId','dueDate','createdBy','createdAt','description','notes','formTemplate.name','formTemplate.status','updatedAt']
df_subset = df_forms_filtered[cols_to_keep]
display(df_subset)

,projectId,id,formNum,formDate,formTemplate.templateType,name,assigneeId,dueDate,createdBy,createdAt,description,notes,formTemplate.name,formTemplate.status,updatedAt
0,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,6211d78f-6460-49df-a5ee-2f7d79520b09,2,2025-09-22,pg.template_type.safety,Daily Safety Inspection,NaN,NaN,SJH2WQKHM47K6GT3,2025-09-22T19:56:10.846181+00:00,NaN,,Daily Safety Inspection,active,2025-09-22T19:56:10.846184+00:00
2,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,866c341c-63d4-45e6-b1c3-7133931d02ea,18,2025-11-12,pg.template_type.safety,Daily Safety Inspection,NaN,NaN,5ZT2JEK8LTP2AEEW,2025-11-12T17:08:24.327976+00:00,NaN,NaN,Daily Safety Inspection,active,2025-11-12T17:08:24.327978+00:00
5,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,76f8d4bd-cd0d-4d0b-94bb-58296244645d,40,2025-12-02,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-02,5ZT2JEK8LTP2AEEW,2025-12-02T22:53:19.198874+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-02T22:58:22.631699+00:00
6,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,60f9ca92-a4ae-42a2-9865-f7d5b97e8bf0,46,2025-12-09,pg.template_type.safety,Daily Safety Inspection,NaN,NaN,5ZT2JEK8LTP2AEEW,2025-12-09T18:07:50.597435+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-09T18:12:40.943571+00:00
7,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,8588fa0d-08aa-45f4-be38-f1444276d68c,48,2025-12-10,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-10,5ZT2JEK8LTP2AEEW,2025-12-10T23:37:05.225938+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-10T23:41:14.142292+00:00
8,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,09a4fd92-b0dc-4c7f-a2cf-cb80fae6abfe,50,2025-12-11,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-11,5ZT2JEK8LTP2AEEW,2025-12-11T22:34:21.395497+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-11T22:37:26.763323+00:00
9,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f92b5fec-2c5c-4e36-acdf-a933df57c59f,52,2025-12-15,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-15,5ZT2JEK8LTP2AEEW,2025-12-15T23:04:33.230132+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-15T23:08:00.702156+00:00
10,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,92c8f7ea-80b3-4002-a19b-3a4b34ab4629,54,2025-12-16,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-16,5ZT2JEK8LTP2AEEW,2025-12-16T23:14:02.902483+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-16T23:16:49.322815+00:00
11,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,aa979fad-ef2a-4f52-a3df-4669da519322,56,2025-12-17,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-17,5ZT2JEK8LTP2AEEW,2025-12-17T22:52:00.005189+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-17T22:56:06.201189+00:00
12,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,d4a11022-7cbc-45b9-845b-e8a6263c5818,57,2025-12-18,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-18,5ZT2JEK8LTP2AEEW,2025-12-18T22:32:12.251707+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-18T22:35:28.322001+00:00
13,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,4028918e-4fd6-4dfb-9648-b30aadf043e4,60,2025-12-19,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-19,5ZT2JEK8LTP2AEEW,2025-12-19T21:34:44.250339+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-19T21:37:45.787876+00:00
14,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,b2a4ae10-f50f-4e5e-9541-b6077760c450,64,2025-12-29,pg.template_type.safety,EHS Violation Warning,4ZHJ2BG2PSMQNDKT,NaN,4ZHJ2BG2PSMQNDKT,2025-12-29T16:59:13.613606+00:00,NaN,NaN,EHS Violation Warning,active,2025-12-29T16:59:13.613608+00:00
15,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f690bfa0-8451-4fd4-8030-d32a65c716c1,66,2025-12-29,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-29,5ZT2JEK8LTP2AEEW,2025-12-29T21:54:12.179662+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-29T21:57:15.453062+00:00
18,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,5c77855c-04e2-4b70-8575-d51b6d7540dc,84,2026-01-09,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-09,5ZT2JEK8LTP2AEEW,2026-01-09T22:04:07.205232+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-09T22:11:50.697085+00:00
19,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,35343724-8847-4787-b1c9-072fdbeeae36,80,2026-01-08,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-08,5ZT2JEK8LTP2AEEW,2026-01-08T22:35:06.167141+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-09T22:28:37.759947+00:00
20,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,e04ce04d-17dd-4487-a8c7-000238d8c3c1,74,2026-01-06,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-06,5ZT2JEK8LTP2AEEW,2026-01-07T02:08:24.072110+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-09T22:41:34.065458+00:00
21,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,b66817d2-66eb-4ec6-b885-a6cec2bc1dea,24,2025-11-14,pg.template_type.safety,Daily Safety Inspection,NaN,2025-11-14,5ZT2JEK8LTP2AEEW,2025-11-14T20:10:35.023101+00:00,De -Watering and maintaining SWPPP requirements,NaN,Daily Safety Inspection,active,2026-01-10T15:31:48.985414+00:00
22,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,9338823a-9b7d-46ef-b779-14ed73715ffb,72,2026-01-05,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-05,5ZT2JEK8LTP2AEEW,2026-01-06T01:16:49.310544+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-10T15:35:42.658092+00:00
23,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,2b5c2438-87f8-4127-a9fc-950227eed960,70,2026-01-02,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-02,5ZT2JEK8LTP2AEEW,2026-01-02T15:42:43.482782+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-10T15:43:33.374986+00:00
24,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,bdcafd4b-06e0-41f9-831b-803b273d34e9,86,2026-01-12,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-12,5ZT2JEK8LTP2AEEW,2026-01-12T23:01:38.466578+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-12T23:07:25.645664+00:00
25,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,308b85f2-47b1-4496-8504-a657af78bf15,88,2026-01-13,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-13,5ZT2JEK8LTP2AEEW,2026-01-13T17:56:04.237085+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-13T17:59:38.627691+00:00
26,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,0777ec89-47ea-42a6-8a1f-06b79f9a9cb5,41,2025-12-03,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-03,5ZT2JEK8LTP2AEEW,2025-12-03T15:43:57.974036+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-14T16:39:39.659698+00:00
27,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,ade095db-3247-497a-b64f-27af6a6df106,20,2025-11-12,pg.template_type.safety,Daily Safety Inspection,NaN,NaN,5ZT2JEK8LTP2AEEW,2025-11-12T17:24:39.108728+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-14T16:44:33.561618+00:00
28,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,7b1fba8d-29b3-4099-b7a1-b83953c703c4,68,2025-12-31,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-31,5ZT2JEK8LTP2AEEW,2026-01-01T02:18:36.180937+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-14T16:59:11.878940+00:00
31,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,c4f00682-8f53-41ef-a762-708f33b73212,92,2026-01-15,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-15,5ZT2JEK8LTP2AEEW,2026-01-15T14:53:23.014829+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-15T22:45:56.889832+00:00
32,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,77dbbe01-6ca0-4f8e-b8e2-d3b84597749f,94,2026-01-16,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-16,5ZT2JEK8LTP2AEEW,2026-01-16T14:59:37.599546+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-16T21:10:57.215959+00:00
33,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,08aeb746-65b8-4706-b7e3-f5dc9725a9ed,96,2026-01-20,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-20,5ZT2JEK8LTP2AEEW,2026-01-20T21:27:33.072984+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-20T21:31:42.783850+00:00
34,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,3c7a0544-ea01-42e7-9f55-fe2f0e127840,98,2026-01-21,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-21,5ZT2JEK8LTP2AEEW,2026-01-21T21:10:09.285829+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-21T21:13:11.558094+00:00
35,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,d055bac6-bfa9-4552-a0cc-b8efdff247a9,100,2026-01-22,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-22,5ZT2JEK8LTP2AEEW,2026-01-22T19:17:16.796166+00:00,NaN,NaN,Safety Daily Inspection,active,2026-01-22T19:22:10.352185+00:00
36,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,c47ab3cc-19dd-469b-88ce-400bc1b228e7,103,2026-01-24,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-24,5ZT2JEK8LTP2AEEW,2026-01-24T15:51:26.146947+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-24T23:15:55.549712+00:00
38,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f62c5bc9-6b94-4b3a-96b5-94c2df9277f7,107,2026-01-26,pg.template_type.safety,Daily Safety Inspection,NaN,NaN,W2G2VE44QUKE49JR,2026-01-26T20:45:26.023229+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-26T21:02:43.566358+00:00
39,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f0d00afa-f66b-4d1f-9a48-b87bef3646f8,105,2026-01-26,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-26,5ZT2JEK8LTP2AEEW,2026-01-26T15:56:01.645786+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-26T22:09:24.678771+00:00
40,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,956e475a-305a-435a-ab3e-df85d12c60f5,109,2026-01-27,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-27,5ZT2JEK8LTP2AEEW,2026-01-27T14:34:46.148476+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-27T22:29:17.998287+00:00
42,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,d94fb011-db9e-4f6f-80c9-b3ac289b403d,112,2026-01-28,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-28,5ZT2JEK8LTP2AEEW,2026-01-28T17:40:26.573845+00:00,NaN,,Daily Safety Inspection,active,2026-01-28T21:35:37.763893+00:00
43,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,c0a6148e-16ae-4c65-a84d-8203b1fe8d5d,115,2026-01-29,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-29,5ZT2JEK8LTP2AEEW,2026-01-29T14:41:59.145956+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-29T22:47:07.189669+00:00
44,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,ba042446-706c-4861-9104-b62bb4f50dba,117,2026-01-30,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-30,5ZT2JEK8LTP2AEEW,2026-01-30T15:07:31.131282+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-30T22:39:15.235828+00:00
45,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,afea122d-91f4-401d-bc56-b6895c2c9a78,90,2026-01-14,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-14,5ZT2JEK8LTP2AEEW,2026-01-14T14:50:13.931011+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-30T23:05:35.637221+00:00

In [21]:
display(df_projects)

,id,accountId,addressLine1,addressLine2,adminGroupId,businessUnitId,city,classification,companyCount,constructionType,...,products,sheetCount,startDate,stateOrProvince,status,templateId,thumbnailImageUrl,timezone,type,updatedAt
0,113c146f-a524-40d8-b6b4-981ec3b82b46,ff580791-c0f5-4839-954c-11cd09d8cf69,,,74965853,758ce31a-47dd-4de8-9400-e102f7d6ccf9,,sample,1,New Construction,...,[{'icon': 'https://bim360-ea-ue1-prod-storage....,NaN,2019-01-01,,archived,NaN,https://bim360-ea-ue1-prod-storage.s3.amazonaw...,America/New_York,Training Project,2024-05-08T15:53:25.139Z
1,93409392-4174-48b9-a273-a0c3fb292827,ff580791-c0f5-4839-954c-11cd09d8cf69,,,35763021,NaN,,production,1,New Construction,...,[{'icon': 'https://bim360-ea-ue1-prod-storage....,NaN,2018-05-01,,archived,NaN,https://bim360-ea-ue1-prod-storage.s3.amazonaw...,America/New_York,Education Facility,2025-09-08T09:47:19.147Z
2,0cea52fc-5c3c-408b-9a13-12b67739ea58,ff580791-c0f5-4839-954c-11cd09d8cf69,1808 North Shoreline Boulevard,NaN,720027871,071d1b1e-fd3c-4543-b08c-af1ebfa93848,Mountain View,production,1,NaN,...,"[{'key': 'docs', 'name': 'Docs', 'status': 'ac...",NaN,2026-03-26,CA,active,8864cf55-2e0d-4bcb-b1c8-30c2683f5512,https://bim360-ea-ue1-prod-storage.s3.amazonaw...,America/Los_Angeles,Google,2026-03-30T22:21:08.553Z
3,beadc983-4dea-4532-a1f1-1164cef78db0,ff580791-c0f5-4839-954c-11cd09d8cf69,NaN,NaN,150384827,NaN,NaN,production,1,NaN,...,"[{'key': 'docs', 'name': 'Docs', 'status': 'ac...",NaN,NaN,NaN,archived,NaN,https://bim360-ea-ue1-prod-storage.s3.amazonaw...,America/Los_Angeles,Office,2022-10-24T18:08:40.007Z
4,61a04114-7cf8-4c30-a446-0e8c6db66f5e,ff580791-c0f5-4839-954c-11cd09d8cf69,Pier 70,Building 12,65769759,NaN,San Francisco,production,1,Renovation,...,[{'icon': 'https://bim360-ea-ue1-prod-storage....,NaN,NaN,CA,archived,NaN,https://bim360-ea-ue1-prod-storage.s3.amazonaw...,America/New_York,Seaport,2025-09-08T09:32:18.248Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,95ca8aba-10cc-47fe-92dc-f752943cc54c,ff580791-c0f5-4839-954c-11cd09d8cf69,851 Buckeye Court,NaN,535041326,NaN,Milpitas,sample,5,NaN,...,"[{'key': 'docs', 'name': 'Docs', 'status': 'ac...",17.0,2025-05-27,CA,active,NaN,https://bim360-ea-ue1-prod-storage.s3.amazonaw...,America/Los_Angeles,Training Project,2025-06-10T17:49:31.155Z
243,5200cb9f-fa01-4c33-9f23-ed3bb2be0341,ff580791-c0f5-4839-954c-11cd09d8cf69,1030 R Street,NaN,545466226,NaN,Sacramento,sample,4,NaN,...,"[{'key': 'docs', 'name': 'Docs', 'status': 'ac...",480.0,2025-06-17,CA,active,1c7fa6b2-fa5d-4952-8ddb-fc500a934c69,https://bim360-ea-ue1-prod-storage.s3.amazonaw...,America/Los_Angeles,Training Project,2025-10-16T18:29:52.649Z
244,ca47d71a-22dc-4c08-ae45-8b8b831f9fb2,ff580791-c0f5-4839-954c-11cd09d8cf69,NaN,NaN,654851971,NaN,NaN,production,1,NaN,...,"[{'key': 'docs', 'name': 'Docs', 'status': 'ac...",NaN,NaN,NaN,archived,f36cf1ae-8ff7-48b7-bf7a-fca9335762ac,https://bim360-ea-ue1-prod-storage.s3.amazonaw...,America/Los_Angeles,Office,2026-01-08T19:57:41.203Z
245,96133c49-f96b-41f0-a6b5-270859a18999,ff580791-c0f5-4839-954c-11cd09d8cf69,NaN,NaN,654894182,NaN,NaN,production,1,NaN,...,"[{'key': 'docs', 'name': 'Docs', 'status': 'ac...",NaN,NaN,NaN,archived,f36cf1ae-8ff7-48b7-bf7a-fca9335762ac,https://bim360-ea-ue1-prod-storage.s3.amazonaw...,America/Los_Angeles,Google,2026-04-28T17:47:10.874Z
246,250a3f19-63f4-4256-ace4-e15dfe497f29,ff580791-c0f5-4839-954c-11cd09d8cf69,,,86816079,bebc508d-e88d-4621-b8b8-bdb68b5d00b6,,production,1,New Construction,...,[{'icon': 'https://bim360-ea-ue1-prod-storage....,NaN,NaN,,archived,NaN,https://bim360-ea-ue1-prod-storage.s3.amazonaw...,America/New_York,Education Facility,2024-10-07T21:03:02.597Z

In [ ]:
df_merged = df_subset.merge(
    df_projects[['id', 'jobNumber']],
    how='left',
    left_on='projectId',
    right_on='id'
)

df_merged = df_merged.drop(columns=['id_y'])
display(df_merged)

,projectId,id_x,formNum,formDate,formTemplate.templateType,name,assigneeId,dueDate,createdBy,createdAt,description,notes,formTemplate.name,formTemplate.status,updatedAt,jobNumber
0,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,6211d78f-6460-49df-a5ee-2f7d79520b09,2,2025-09-22,pg.template_type.safety,Daily Safety Inspection,NaN,NaN,SJH2WQKHM47K6GT3,2025-09-22T19:56:10.846181+00:00,NaN,,Daily Safety Inspection,active,2025-09-22T19:56:10.846184+00:00,4844
1,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,866c341c-63d4-45e6-b1c3-7133931d02ea,18,2025-11-12,pg.template_type.safety,Daily Safety Inspection,NaN,NaN,5ZT2JEK8LTP2AEEW,2025-11-12T17:08:24.327976+00:00,NaN,NaN,Daily Safety Inspection,active,2025-11-12T17:08:24.327978+00:00,4844
2,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,76f8d4bd-cd0d-4d0b-94bb-58296244645d,40,2025-12-02,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-02,5ZT2JEK8LTP2AEEW,2025-12-02T22:53:19.198874+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-02T22:58:22.631699+00:00,4844
3,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,60f9ca92-a4ae-42a2-9865-f7d5b97e8bf0,46,2025-12-09,pg.template_type.safety,Daily Safety Inspection,NaN,NaN,5ZT2JEK8LTP2AEEW,2025-12-09T18:07:50.597435+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-09T18:12:40.943571+00:00,4844
4,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,8588fa0d-08aa-45f4-be38-f1444276d68c,48,2025-12-10,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-10,5ZT2JEK8LTP2AEEW,2025-12-10T23:37:05.225938+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-10T23:41:14.142292+00:00,4844
5,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,09a4fd92-b0dc-4c7f-a2cf-cb80fae6abfe,50,2025-12-11,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-11,5ZT2JEK8LTP2AEEW,2025-12-11T22:34:21.395497+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-11T22:37:26.763323+00:00,4844
6,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f92b5fec-2c5c-4e36-acdf-a933df57c59f,52,2025-12-15,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-15,5ZT2JEK8LTP2AEEW,2025-12-15T23:04:33.230132+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-15T23:08:00.702156+00:00,4844
7,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,92c8f7ea-80b3-4002-a19b-3a4b34ab4629,54,2025-12-16,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-16,5ZT2JEK8LTP2AEEW,2025-12-16T23:14:02.902483+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-16T23:16:49.322815+00:00,4844
8,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,aa979fad-ef2a-4f52-a3df-4669da519322,56,2025-12-17,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-17,5ZT2JEK8LTP2AEEW,2025-12-17T22:52:00.005189+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-17T22:56:06.201189+00:00,4844
9,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,d4a11022-7cbc-45b9-845b-e8a6263c5818,57,2025-12-18,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-18,5ZT2JEK8LTP2AEEW,2025-12-18T22:32:12.251707+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-18T22:35:28.322001+00:00,4844
10,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,4028918e-4fd6-4dfb-9648-b30aadf043e4,60,2025-12-19,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-19,5ZT2JEK8LTP2AEEW,2025-12-19T21:34:44.250339+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-19T21:37:45.787876+00:00,4844
11,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,b2a4ae10-f50f-4e5e-9541-b6077760c450,64,2025-12-29,pg.template_type.safety,EHS Violation Warning,4ZHJ2BG2PSMQNDKT,NaN,4ZHJ2BG2PSMQNDKT,2025-12-29T16:59:13.613606+00:00,NaN,NaN,EHS Violation Warning,active,2025-12-29T16:59:13.613608+00:00,4844
12,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f690bfa0-8451-4fd4-8030-d32a65c716c1,66,2025-12-29,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-29,5ZT2JEK8LTP2AEEW,2025-12-29T21:54:12.179662+00:00,NaN,NaN,Daily Safety Inspection,active,2025-12-29T21:57:15.453062+00:00,4844
13,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,5c77855c-04e2-4b70-8575-d51b6d7540dc,84,2026-01-09,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-09,5ZT2JEK8LTP2AEEW,2026-01-09T22:04:07.205232+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-09T22:11:50.697085+00:00,4844
14,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,35343724-8847-4787-b1c9-072fdbeeae36,80,2026-01-08,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-08,5ZT2JEK8LTP2AEEW,2026-01-08T22:35:06.167141+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-09T22:28:37.759947+00:00,4844
15,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,e04ce04d-17dd-4487-a8c7-000238d8c3c1,74,2026-01-06,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-06,5ZT2JEK8LTP2AEEW,2026-01-07T02:08:24.072110+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-09T22:41:34.065458+00:00,4844
16,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,b66817d2-66eb-4ec6-b885-a6cec2bc1dea,24,2025-11-14,pg.template_type.safety,Daily Safety Inspection,NaN,2025-11-14,5ZT2JEK8LTP2AEEW,2025-11-14T20:10:35.023101+00:00,De -Watering and maintaining SWPPP requirements,NaN,Daily Safety Inspection,active,2026-01-10T15:31:48.985414+00:00,4844
17,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,9338823a-9b7d-46ef-b779-14ed73715ffb,72,2026-01-05,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-05,5ZT2JEK8LTP2AEEW,2026-01-06T01:16:49.310544+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-10T15:35:42.658092+00:00,4844
18,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,2b5c2438-87f8-4127-a9fc-950227eed960,70,2026-01-02,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-02,5ZT2JEK8LTP2AEEW,2026-01-02T15:42:43.482782+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-10T15:43:33.374986+00:00,4844
19,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,bdcafd4b-06e0-41f9-831b-803b273d34e9,86,2026-01-12,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-12,5ZT2JEK8LTP2AEEW,2026-01-12T23:01:38.466578+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-12T23:07:25.645664+00:00,4844
20,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,308b85f2-47b1-4496-8504-a657af78bf15,88,2026-01-13,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-13,5ZT2JEK8LTP2AEEW,2026-01-13T17:56:04.237085+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-13T17:59:38.627691+00:00,4844
21,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,0777ec89-47ea-42a6-8a1f-06b79f9a9cb5,41,2025-12-03,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-03,5ZT2JEK8LTP2AEEW,2025-12-03T15:43:57.974036+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-14T16:39:39.659698+00:00,4844
22,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,ade095db-3247-497a-b64f-27af6a6df106,20,2025-11-12,pg.template_type.safety,Daily Safety Inspection,NaN,NaN,5ZT2JEK8LTP2AEEW,2025-11-12T17:24:39.108728+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-14T16:44:33.561618+00:00,4844
23,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,7b1fba8d-29b3-4099-b7a1-b83953c703c4,68,2025-12-31,pg.template_type.safety,Daily Safety Inspection,NaN,2025-12-31,5ZT2JEK8LTP2AEEW,2026-01-01T02:18:36.180937+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-14T16:59:11.878940+00:00,4844
24,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,c4f00682-8f53-41ef-a762-708f33b73212,92,2026-01-15,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-15,5ZT2JEK8LTP2AEEW,2026-01-15T14:53:23.014829+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-15T22:45:56.889832+00:00,4844
25,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,77dbbe01-6ca0-4f8e-b8e2-d3b84597749f,94,2026-01-16,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-16,5ZT2JEK8LTP2AEEW,2026-01-16T14:59:37.599546+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-16T21:10:57.215959+00:00,4844
26,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,08aeb746-65b8-4706-b7e3-f5dc9725a9ed,96,2026-01-20,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-20,5ZT2JEK8LTP2AEEW,2026-01-20T21:27:33.072984+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-20T21:31:42.783850+00:00,4844
27,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,3c7a0544-ea01-42e7-9f55-fe2f0e127840,98,2026-01-21,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-21,5ZT2JEK8LTP2AEEW,2026-01-21T21:10:09.285829+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-21T21:13:11.558094+00:00,4844
28,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,d055bac6-bfa9-4552-a0cc-b8efdff247a9,100,2026-01-22,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-22,5ZT2JEK8LTP2AEEW,2026-01-22T19:17:16.796166+00:00,NaN,NaN,Safety Daily Inspection,active,2026-01-22T19:22:10.352185+00:00,4844
29,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,c47ab3cc-19dd-469b-88ce-400bc1b228e7,103,2026-01-24,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-24,5ZT2JEK8LTP2AEEW,2026-01-24T15:51:26.146947+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-24T23:15:55.549712+00:00,4844
30,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f62c5bc9-6b94-4b3a-96b5-94c2df9277f7,107,2026-01-26,pg.template_type.safety,Daily Safety Inspection,NaN,NaN,W2G2VE44QUKE49JR,2026-01-26T20:45:26.023229+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-26T21:02:43.566358+00:00,4844
31,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,f0d00afa-f66b-4d1f-9a48-b87bef3646f8,105,2026-01-26,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-26,5ZT2JEK8LTP2AEEW,2026-01-26T15:56:01.645786+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-26T22:09:24.678771+00:00,4844
32,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,956e475a-305a-435a-ab3e-df85d12c60f5,109,2026-01-27,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-27,5ZT2JEK8LTP2AEEW,2026-01-27T14:34:46.148476+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-27T22:29:17.998287+00:00,4844
33,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,d94fb011-db9e-4f6f-80c9-b3ac289b403d,112,2026-01-28,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-28,5ZT2JEK8LTP2AEEW,2026-01-28T17:40:26.573845+00:00,NaN,,Daily Safety Inspection,active,2026-01-28T21:35:37.763893+00:00,4844
34,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,c0a6148e-16ae-4c65-a84d-8203b1fe8d5d,115,2026-01-29,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-29,5ZT2JEK8LTP2AEEW,2026-01-29T14:41:59.145956+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-29T22:47:07.189669+00:00,4844
35,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,ba042446-706c-4861-9104-b62bb4f50dba,117,2026-01-30,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-30,5ZT2JEK8LTP2AEEW,2026-01-30T15:07:31.131282+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-30T22:39:15.235828+00:00,4844
36,b2af28b4-2a18-453e-8b28-1ed8f6a7fd6c,afea122d-91f4-401d-bc56-b6895c2c9a78,90,2026-01-14,pg.template_type.safety,Daily Safety Inspection,NaN,2026-01-14,5ZT2JEK8LTP2AEEW,2026-01-14T14:50:13.931011+00:00,NaN,NaN,Daily Safety Inspection,active,2026-01-30T23:05:35.637221+00:00,4844

In [ ]:
pd.json_normalize(df_forms_filtered["customValues"].explode())

,fieldId,sectionLabel,itemLabel,valueName,valueOptions,arrayVal,notes,updatedAt,updatedBy,dateVal,choiceVal
0,5e9b032d-9fc7-45e3-b82d-58ed275eaafb,Form Data,Person(s) Collaborating on this Daily Inspection,arrayVal,"[PE / Sr. PE, FE / Sr. FE, APM / PM / SPM, Saf...",NaN,NaN,NaN,NaN,NaN,NaN
0,d7ca772c-420e-4fb7-8035-216684131170,Form Data,Date Completed,dateVal,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,56035b14-d6d5-4500-b59d-fd54b7fb6f55,Employee Observation / PPE,Hard Hats,choiceVal,"[Satisfactory, Action Required, Not Applicable...",NaN,NaN,NaN,NaN,NaN,NaN
0,201ea173-a1e2-462b-87f0-e499ee803dda,Employee Observation / PPE,Eye / Face Protection,choiceVal,"[Satisfactory, Action Required, Not Applicable...",NaN,NaN,NaN,NaN,NaN,NaN
0,a95b2ffc-5e34-48b9-8bd7-8aa8083b67f3,Employee Observation / PPE,Ear Protection,choiceVal,"[Satisfactory, Action Required, Not Applicable...",NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
45,0f06c5c6-9874-456a-8cd9-4bd085551a21,Programs / Information,Jobsite Safety Meeting,choiceVal,"[Satisfactory, Action Required, Not Applicable...",NaN,NaN,NaN,NaN,NaN,NaN
45,079ae1f9-73a2-4b42-a8b7-13e017394ad4,Programs / Information,Pre-Task Meetings,choiceVal,"[Satisfactory, Action Required, Not Applicable...",NaN,NaN,NaN,NaN,NaN,NaN
45,6c3e1558-9a23-48fd-8dd5-7715fb5680bf,Programs / Information,Stretch & Flex,choiceVal,"[Satisfactory, Action Required, Not Applicable...",NaN,NaN,NaN,NaN,NaN,NaN
45,bad64545-1971-4fea-868d-ec0b55cf8d57,Programs / Information,Fall Protection Plans,choiceVal,"[Satisfactory, Action Required, Not Applicable...",NaN,NaN,NaN,NaN,NaN,NaN
45,6a9b69d3-b2cd-478a-8bca-4ff73b31acb7,Programs / Information,Rest Periods,choiceVal,"[Satisfactory, Action Required, Not Applicable...",NaN,NaN,NaN,NaN,NaN,NaN